### ISSUE TITLE
Missing module "zope.interface" for Twisted when running example code

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/sanity-nupic#13]
I followed these directions to install:

``` sh
cd sanity-nupic
git submodule update --init --recursive
brew install leiningen
python setup.py develop --user
cd htmsanity/nupic/sanity
lein cljsbuild once demos
cd ../../..
python examples/hotgym.py
```

And I get this error:

```
Traceback (most recent call last):
  File "examples/hotgym.py", line 5, in <module>
    from htmsanity.nupic.runner import SanityRunner
  File "/Users/mtaylor/nta/sanity-nupic/htmsanity/nupic/runner.py", line 10, in <module>
    from autobahn.twisted.websocket import WebSocketServerFactory
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/autobahn-0.14.0-py2.7.egg/autobahn/twisted/__init__.py", line 33, in <module>
    import twisted
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/twisted/__init__.py", line 55, in <module>
    _checkRequirements()
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/twisted/__init__.py", line 39, in _checkRequirements
    raise ImportError(required + ": no module named zope.interface.")
ImportError: Twisted requires zope.interface 3.6.0 or later: no module named zope.interface.
```

Twisted 16.2.0 is installed (I also tried uninstalling and re-installing). `easy_install zope.interface` as [suggested here](http://stackoverflow.com/a/14637032/154560) did not help.

**Comment by mrcslws** [comment]
Interesting. When I do `pip show zope.interface` I get:

```
Metadata-Version: 1.1
Name: zope.interface
Version: 4.1.1
Summary: Interfaces for Python
Home-page: http://pypi.python.org/pypi/zope.interface
Author: Zope Foundation and Contributors
Author-email: zope-dev@zope.org
License: ZPL 2.1
Location: /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
Requires: setuptools
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  License :: OSI Approved :: Zope Public License
  Operating System :: OS Independent
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.2
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: Implementation :: CPython
  Programming Language :: Python :: Implementation :: PyPy
  Framework :: Zope3
  Topic :: Software Development :: Libraries :: Python Modules
```

So it's installed in my system path. I think it was part of my laptop's default Python installation. Does this info help? Maybe you have an old version in your system path?

**Comment by mrcslws** [comment]
I don't think this is still an issue. Feel free to reopen.

**Comment by yideg-tech** [comment]
O h good
